# Generated by Django 5.2.4 on 2026-05-03 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact-images/')),
                ('reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'Received'), ('Solved', 'Solved')], default='Submitted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
