# Generated by Django 5.2.4 on 2026-05-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_hashed',
            field=models.CharField(max_length=255),
        ),
    ]
