# Generated by Django 5.2.4 on 2026-05-04 12:49

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction_items/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sold', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Sold', 'Sold'), ('Not Sold', 'Not Sold'), ('Pass', 'Pass')], default='Pending', max_length=20)),
                ('duration', models.IntegerField(default=60)),
                ('ends_at', models.DateTimeField(null=True)),
                ('extension_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionRoom',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Closed', 'Closed')], default='Draft', max_length=50)),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_private', models.BooleanField(default=False)),
                ('access_code', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Outbid', 'Outbid'), ('Won', 'Won')], default='Outbid', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('is_winning', models.BooleanField(default=False)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-bid_amount'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_wishlist', models.BooleanField(default=False)),
            ],
        ),
    ]
