# Generated by Django 6.0.3 on 2026-04-18 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_item', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionroom',
            name='end_time',
            field=models.DateTimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='auctionroom',
            name='start_time',
            field=models.DateTimeField(default=datetime.time(18, 0)),
        ),
    ]
