# Generated by Django 5.2.4 on 2026-05-06 16:22

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_item', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPanel',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_accepted', models.CharField(choices=[('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Rejected', 'Rejected')], default='Denied', max_length=15)),
                ('max_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_item.auctionitem')),
                ('request_panel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_item.auctionroom')),
            ],
        ),
    ]
