# Generated by Django 5.2.4 on 2026-05-31 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_item', '0003_alter_auctionitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='duration',
            field=models.IntegerField(db_index=True, default=60),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='ends_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='extension_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='is_sold',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Sold', 'Sold'), ('Not Sold', 'Not Sold'), ('Pass', 'Pass')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='auctionroom',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auctionroom',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auctionroom',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Closed', 'Closed')], db_index=True, default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='bid',
            name='is_winning',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Outbid', 'Outbid'), ('Won', 'Won')], db_index=True, default='Outbid', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestpanel',
            name='dislikes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='requestpanel',
            name='is_accepted',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='requestpanel',
            name='likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['auction_room', 'is_sold'], name='auction_ite_auction_7fcc21_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['auction_room', 'order'], name='auction_ite_auction_367251_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction_item', 'is_winning'], name='auction_ite_auction_bae6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction_item', '-bid_amount'], name='auction_ite_auction_9b1e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', 'status'], name='auction_ite_bidder__ac8d82_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['auction', '-created_at'], name='auction_ite_auction_97e1dc_idx'),
        ),
    ]
