# Generated by Django 6.0.3 on 2026-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_item', '0004_alter_auctionroom_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='ends_at',
            field=models.IntegerField(default=0),
        ),
    ]
