# Generated by Django 6.0.3 on 2026-04-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_item', '0005_alter_auctionitem_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='duration',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='ends_at',
            field=models.DateTimeField(null=True),
        ),
    ]
