# Generated by Django 6.0.3 on 2026-04-27 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_item', '0007_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wishlist', models.BooleanField(default=False)),
                ('auction_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_wishlist', to='auction_item.auctionitem')),
                ('auction_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_wishlist', to='auction_item.auctionroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'auction_item')},
            },
        ),
    ]
