# Generated by Django 6.0.3 on 2026-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_item', '0008_alter_auctionitem_duration_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='extension_count',
            field=models.IntegerField(default=0),
        ),
    ]
